package storage

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/greycoderk/lore/internal/domain"
)

func TestRegenerateIndex_EmptyDir(t *testing.T) {
	dir := t.TempDir()

	if err := RegenerateIndex(dir); err != nil {
		t.Fatalf("index: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "README.md"))
	if err != nil {
		t.Fatalf("read readme: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Lore Documentation Index") {
		t.Error("expected index header")
	}
	if !strings.Contains(content, "0 documents total") {
		t.Error("expected 0 documents count")
	}
}

func TestRegenerateIndex_WithDocuments(t *testing.T) {
	dir := t.TempDir()

	// Write 3 docs with different dates
	_, _ = WriteDoc(dir, domain.DocMeta{Type: "decision", Date: "2026-03-05", Status: "published", Tags: []string{"auth"}}, "older", "body\n")
	_, _ = WriteDoc(dir, domain.DocMeta{Type: "feature", Date: "2026-03-07", Status: "published", Tags: []string{"api"}}, "mid", "body\n")
	_, _ = WriteDoc(dir, domain.DocMeta{Type: "note", Date: "2026-03-10", Status: "draft"}, "newest", "body\n")

	// RegenerateIndex is called by WriteDoc, but call explicitly to verify
	if err := RegenerateIndex(dir); err != nil {
		t.Fatalf("index: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "README.md"))
	if err != nil {
		t.Fatalf("read readme: %v", err)
	}

	content := string(data)

	// Check header
	if !strings.Contains(content, "Auto-generated by `lore`") {
		t.Error("expected auto-generated note")
	}

	// Check table headers
	if !strings.Contains(content, "| Document | Type | Date | Status | Tags |") {
		t.Error("expected table header")
	}

	// Check documents are listed
	if !strings.Contains(content, "decision") {
		t.Error("expected decision type in index")
	}
	if !strings.Contains(content, "feature") {
		t.Error("expected feature type in index")
	}

	// Check sort order (newest first)
	noteIdx := strings.Index(content, "2026-03-10")
	decisionIdx := strings.Index(content, "2026-03-05")
	if noteIdx > decisionIdx {
		t.Error("expected newest date first (descending sort)")
	}

	// Check count
	if !strings.Contains(content, "3 documents total") {
		t.Errorf("expected '3 documents total', got:\n%s", content)
	}
}

func TestRegenerateIndex_Idempotent(t *testing.T) {
	dir := t.TempDir()

	WriteDoc(dir, domain.DocMeta{Type: "decision", Date: "2026-03-07", Status: "published"}, "doc", "body\n")

	// First call
	if err := RegenerateIndex(dir); err != nil {
		t.Fatalf("first index: %v", err)
	}
	data1, _ := os.ReadFile(filepath.Join(dir, "README.md"))

	// Second call
	if err := RegenerateIndex(dir); err != nil {
		t.Fatalf("second index: %v", err)
	}
	data2, _ := os.ReadFile(filepath.Join(dir, "README.md"))

	if string(data1) != string(data2) {
		t.Error("index should be idempotent — two calls should produce identical content")
	}
}

func TestRegenerateIndex_NonExistentDir(t *testing.T) {
	err := RegenerateIndex("/nonexistent/path/that/doesnt/exist")
	if err != nil {
		t.Errorf("non-existent dir should return nil, got: %v", err)
	}
}

// TestRegenerateIndex_PartialOnCorruptedFile verifies N1 fix: when a .md file
// cannot be parsed, RegenerateIndex still writes the index with the valid files
// and returns the parse error — a partial index is better than no update.
func TestRegenerateIndex_PartialOnCorruptedFile(t *testing.T) {
	dir := t.TempDir()

	// Write one valid doc
	WriteDoc(dir, domain.DocMeta{Type: "decision", Date: "2026-03-07", Status: "published"}, "valid", "body\n")

	// Inject a corrupted .md file (no front matter delimiter)
	if err := os.WriteFile(filepath.Join(dir, "corrupted.md"), []byte("no front matter here"), 0o644); err != nil {
		t.Fatalf("write corrupted: %v", err)
	}

	err := RegenerateIndex(dir)
	if err == nil {
		t.Error("expected error for corrupted file, got nil")
	}

	// Index must still be written with the parseable doc
	data, readErr := os.ReadFile(filepath.Join(dir, "README.md"))
	if readErr != nil {
		t.Fatalf("README.md should be written even with corrupted files: %v", readErr)
	}
	content := string(data)
	if !strings.Contains(content, "1 document total") {
		t.Errorf("expected partial index with '1 document total', got:\n%s", content)
	}
	if !strings.Contains(content, "decision") {
		t.Errorf("expected valid doc in partial index, got:\n%s", content)
	}
}

func TestRegenerateIndex_TagsDisplayed(t *testing.T) {
	dir := t.TempDir()

	WriteDoc(dir, domain.DocMeta{
		Type:   "decision",
		Date:   "2026-03-07",
		Status: "published",
		Tags:   []string{"authentication", "api"},
	}, "auth strategy", "body\n")

	RegenerateIndex(dir)

	data, _ := os.ReadFile(filepath.Join(dir, "README.md"))
	content := string(data)

	if !strings.Contains(content, "authentication, api") {
		t.Errorf("expected tags in index, got:\n%s", content)
	}
}
