// Copyright (C) 2026 Museigen
// SPDX-License-Identifier: AGPL-3.0-or-later

package storage

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RegenerateIndex creates or updates the README.md index in docsDir.
// It scans all .md files (except README.md), parses their front matter,
// and generates a sorted table. The result is written atomically.
func RegenerateIndex(docsDir string) error {
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("storage: index %s: %w", docsDir, err)
	}

	type docEntry struct {
		Filename string
		Type     string
		Date     string
		Status   string
		Tags     string
	}

	var docs []docEntry
	var parseErrs []error
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".md") || name == "README.md" {
			continue
		}

		data, err := os.ReadFile(filepath.Join(docsDir, name))
		if err != nil {
			parseErrs = append(parseErrs, fmt.Errorf("storage: index: read %s: %w", name, err))
			continue
		}

		meta, _, err := Unmarshal(data)
		if err != nil {
			parseErrs = append(parseErrs, fmt.Errorf("storage: index: parse %s: %w", name, err))
			continue
		}

		docs = append(docs, docEntry{
			Filename: name,
			Type:     meta.Type,
			Date:     meta.Date,
			Status:   meta.Status,
			Tags:     strings.Join(meta.Tags, ", "),
		})
	}
	// Sort by date descending
	sort.Slice(docs, func(i, j int) bool {
		return docs[i].Date > docs[j].Date
	})

	var buf strings.Builder
	buf.WriteString("# Lore Documentation Index\n\n")
	buf.WriteString("> Auto-generated by `lore`. Do not edit manually.\n\n")
	buf.WriteString("| Document | Type | Date | Status | Tags |\n")
	buf.WriteString("|----------|------|------|--------|------|\n")

	for _, d := range docs {
		fmt.Fprintf(&buf, "| [%s](%s) | %s | %s | %s | %s |\n",
			d.Filename, d.Filename,
			escapeTableCell(d.Type), d.Date, escapeTableCell(d.Status),
			escapeTableCell(d.Tags))
	}

	// N2 fix: correct singular/plural for document count.
	unit := "documents"
	if len(docs) == 1 {
		unit = "document"
	}
	fmt.Fprintf(&buf, "\n*%d %s total*\n", len(docs), unit)

	readmePath := filepath.Join(docsDir, "README.md")
	// N1 fix: write partial index even when some files fail to parse.
	// A partial-but-readable index is better than no update at all.
	// Parse errors are returned after the write so callers can surface them.
	if writeErr := AtomicWrite(readmePath, []byte(buf.String())); writeErr != nil {
		return writeErr
	}
	return errors.Join(parseErrs...)
}

// escapeTableCell escapes pipe characters in markdown table cell values.
func escapeTableCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
