// Copyright (C) 2026 Museigen
// SPDX-License-Identifier: AGPL-3.0-or-later

package i18n

// UIMessages holds strings for terminal UI components (internal/ui/ package).
type UIMessages struct {
	// logo.go
	Tagline string // "your code knows what. lore knows why."

	// error.go
	ErrorPrefix string // "Error:"
	RunPrefix   string // "Run:"

	// verb.go
	VerbDeleted string // "Deleted"

	// list.go
	ListTruncated    string // "... and %d more. Refine your search." (arg: remaining count)
	ListPromptRange  string // "Please enter a number between 1 and %d." (arg: max)
	ListNoInput      string // "no input"

	// prompt.go
	PromptWithDefault string // "? %s [%s]: " (args: question, default)
	PromptNoDefault   string // "? %s\n> " (arg: question)

	// readme_bridge.go
	ReadmeBridgeTitle   string // "About .lore/"
	ReadmeBridgeIntro   string // "This repository is documented with [Lore](...)."
	ReadmeBridgeDesc    string // "Lore captures the *why* behind code changes..."
	ReadmeBridgeLink    string // "Learn more: ..."
	ReadmeBridgeGenNote string // "This file was generated by `lore init`..."

	// interactive fallback
	InteractiveFallback string // "interactive mode not available in non-TTY, falling back to standard output"

	// badge.go
	BadgeCoverageDetail   string // "Coverage: %d%% (%d eligible: %d documented, %d skipped, %d gaps)"
	BadgeNoEligible       string // "no eligible commits"
	BadgeSkipRateWarning  string // "⚠ Skip rate: %d%% (%d/%d eligible commits skipped)"
	BadgeSkipRateHint     string // "A high skip rate may indicate documentation avoidance."
	BadgeLabelDocumented  string // "documented" / "documente"
}
